sonar.projectKey=Mern-Application
sonar.projectName=Mern-Application

sonar.sources=client/app,server

sonar.exclusions=**/node_modules/**,\
**/build/**,\
**/dist/**,\
**/.next/**,\
**/coverage/**,\
**/*.min.js
