name: MERN CD Pipeline

on:
  workflow_dispatch:

  workflow_run:
    workflows:
      - MERN CI Pipeline
    types:
      - completed

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  FRONTEND_REPO: ${{ vars.FRONTEND_REPO }}
  BACKEND_REPO: ${{ vars.BACKEND_REPO }}

jobs:

  deploy:


    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'


    runs-on: self-hosted

    permissions:
      contents: write

    steps:

    ####################################################
    # Checkout GitOps Repository
    ####################################################

    - name: Checkout GitOps Repository
      uses: actions/checkout@v4
      with:
        repository: Lohitht909/application-gitops
        token: ${{ secrets.GH_TOKEN }}

    ####################################################
    # Verify Repository
    ####################################################

    - name: Verify Repository
      run: |
        pwd
        ls -R

    ####################################################
    # Determine Image Tag
    ####################################################

    - name: Set Image Tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=${{ github.event.workflow_run.run_number }}" >> $GITHUB_ENV
        fi

    ####################################################
    # Display Image Tag
    ####################################################

    - name: Display Image Tag
      run: |
        echo "Deploying Image Tag: $IMAGE_TAG"

    ####################################################
    # Update Backend Deployment
    ####################################################

    - name: Update Backend Image
      run: |
        sed -Ei "s|(image: .*mern-backend:).*|\1${IMAGE_TAG}|" backend/deployment.yaml

    ####################################################
    # Update Frontend Deployment
    ####################################################

    - name: Update Frontend Image
      run: |
        sed -Ei "s|(image: .*mern-frontend:).*|\1${IMAGE_TAG}|" frontend/deployment.yaml

    ####################################################
    # Verify Updated Images
    ####################################################

    - name: Verify Updated Images
      run: |
        echo "========== Backend =========="
        grep "image:" backend/deployment.yaml

        echo ""

        echo "========== Frontend =========="
        grep "image:" frontend/deployment.yaml

    ####################################################
    # Configure Git
    ####################################################

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    ####################################################
    # Commit Changes
    ####################################################

    - name: Commit Changes
      run: |
        git add .

        git commit -m "Deploy build ${IMAGE_TAG}" || echo "No changes to commit"

    ####################################################
    # Push Changes
    ####################################################

    - name: Push Changes
      run: |
        git push
